export const SET_GENERATED_OTGOVORKA = "SET_GENERATED_OTGOVORKA";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_IS_LOADING_FAILED = "SET_IS_LOADING_FAILED";
export const SET_COPY_MESSAGE_VISIBLE = "SET_COPY_MESSAGE_VISIBLE";
export const SET_SETTINGS = "SET_SETTINGS";
export const TOGGLE_SETTINGS_VISIBILITY = "TOGGLE_SETTINGS_VISIBILITY";
